# Generated by Django 5.2.14 on 2026-05-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_full_name_user_role_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SYSTEM', 'System Admin'), ('GLOBAL_VIEWER', 'Global Viewer'), ('ADMIN_USER', 'Admin User')], default='ADMIN_USER', max_length=20),
        ),
    ]
