# Generated by Django 5.2.14 on 2026-05-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_newstag_rename_is_published_newsarticle_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='cover_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='news/cover/thumbs/'),
        ),
    ]
