# Generated by Django 5.2.14 on 2026-05-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_page_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
