# Generated by Django 5.2.14 on 2026-05-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_pagesection_eyebrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='primary_button_text',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='primary_button_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='secondary_button_text',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='secondary_button_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
