# Generated by Django 5.2.14 on 2026-05-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_pagesection_image_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('content', 'Content'), ('split_content', 'Split Content'), ('structured_content', 'Structured Content'), ('image', 'Image'), ('cards', 'Cards'), ('values', 'Values'), ('quote', 'Quote'), ('gallery', 'Gallery'), ('cta', 'CTA')], max_length=50),
        ),
    ]
