# Generated by Django 5.2.14 on 2026-05-11 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_pagesection_section_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('landing_feature', 'Landing Feature'), ('content', 'Content'), ('split_content', 'Split Content'), ('structured_content', 'Structured Content'), ('project_location', 'Project Location'), ('image', 'Image'), ('cards', 'Cards'), ('values', 'Values'), ('quote', 'Quote'), ('gallery', 'Gallery'), ('cta', 'CTA')], max_length=50),
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.navigationitem')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.navigationmenu')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
