# Generated by Django 5.2.14 on 2026-05-12 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_navigationmenu_alter_pagesection_section_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('overview', 'Overview'), ('content', 'Content'), ('split_content', 'Split Content'), ('structured_content', 'Structured Content'), ('location', 'Location'), ('map', 'Map'), ('highlights', 'Highlights'), ('cards', 'Cards'), ('gallery', 'Gallery'), ('quote', 'Quote')], max_length=50)),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/sections/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('image_position', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right'), ('background', 'Background')], default='top', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('primary_button_text', models.CharField(blank=True, max_length=120)),
                ('primary_button_url', models.CharField(blank=True, max_length=255)),
                ('secondary_button_text', models.CharField(blank=True, max_length=120)),
                ('secondary_button_url', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.project')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
