# Generated by Django 5.2.14 on 2026-05-13 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_project_seo_description_project_seo_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('subtitle', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/topics/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='cms.newscategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='topics', to='cms.newstag')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
