# Generated by Django 5.2.14 on 2026-05-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_newstopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Karya Wijaya', max_length=160)),
                ('legal_name', models.CharField(default='PT Karya Wijaya', max_length=200)),
                ('tagline', models.CharField(blank=True, default='Integrated digital mining ecosystem.', max_length=255)),
                ('primary_logo', models.ImageField(blank=True, null=True, upload_to='company/logo/')),
                ('white_logo', models.ImageField(blank=True, null=True, upload_to='company/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='company/favicon/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('footer_products', models.JSONField(blank=True, default=list)),
                ('copyright_text', models.CharField(blank=True, max_length=255)),
                ('designer_name', models.CharField(blank=True, max_length=120)),
                ('designer_url', models.CharField(blank=True, max_length=255)),
                ('privacy_policy_url', models.CharField(blank=True, max_length=255)),
                ('cookie_policy_url', models.CharField(blank=True, max_length=255)),
                ('terms_url', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
    ]
