# Generated by Django 5.2.14 on 2026-05-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='x_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
