# Generated by Django 5.2.14 on 2026-05-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_companyprofile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='cookie_policy_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='designer_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='designer_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='footer_products',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='privacy_policy_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='terms_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='x_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
