# Generated by Django 5.2.14 on 2026-05-15 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'media_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], default='IMAGE', max_length=10)),
                ('file', models.FileField(upload_to='media/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/thumbnails/')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Video duration in seconds', null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_covers', to='cms.media')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_albums',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAlbumItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_items', to='cms.mediaalbum')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_items', to='cms.media')),
            ],
            options={
                'db_table': 'media_album_items',
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='media',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='media_items', through='cms.MediaAlbumItem', to='cms.mediaalbum'),
        ),
        migrations.AddField(
            model_name='media',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_items', to='cms.mediacategory'),
        ),
        migrations.AddConstraint(
            model_name='mediaalbumitem',
            constraint=models.UniqueConstraint(fields=('media', 'album'), name='unique_media_album_item'),
        ),
    ]
